[toolchain]
channel = "1.97" # <- updated to support probe-rs-tools requirements (embassy default: 1.85)
components = [
    "rust-src",
    "rustfmt",
] # <- optionally add "llvm-tools-preview" for some extra features like "cargo size"
targets = [
    "thumbv8m.main-none-eabihf", # <- change for your platform
]
