name: Build the project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.95.0
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust components
        run: rustup component add rustfmt clippy

      - name: Install Rust targets
        run: |
          rustup target add thumbv8m.main-none-eabihf
          rustup target add x86_64-unknown-linux-gnu

      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run Cargo check
        run: cargo check --target thumbv8m.main-none-eabihf

      - name: Run Clippy
        run: cargo clippy --bin devminds-lamp --target thumbv8m.main-none-eabihf -- -D warnings

      - name: Run host tests
        run: cargo test --lib --target x86_64-unknown-linux-gnu

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }} --target thumbv8m.main-none-eabihf

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: devminds-lamp-${{ matrix.BUILD_TARGET }}
          path: target/thumbv8m.main-none-eabihf/${{ matrix.BUILD_TARGET }}/devminds-lamp
